### ISSUE TITLE
maven import

### ISSUE THREAD

**Issue by AndoKarim** [eug/imageio-pnm#1]
Hello, do you have the line to add to pom.xml to add as a library your project? 

Thank you.

**Comment by eug** [comment]
Unfortunately, no.

**Comment by AndoKarim** [comment]
Is it possible to add it?(I need it for a school project). 
Thanks again.

**Comment by eug** [comment]
Yes, but not for these days because I'm quite busy on some other projects. If you are interested you can go ahead and add it. You can send me emails to help you on this.
